import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import AuthButtons from '../components/AuthButtons'
import Providers from '../components/Providers'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap" rel="stylesheet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="bg-black text-white" style={{background: 'linear-gradient(180deg,#071021,#061826)', fontFamily: 'Inter, system-ui, -apple-system'}}>
        <Providers>
          <header className="container flex items-center justify-between py-6">
            <div className="flex items-center gap-3">
              <div style={{width:40,height:40,background:'linear-gradient(135deg,#06b6d4,#7c3aed)'}} className="rounded-md" />
              <a href="/" className="font-bold text-lg">Inbound Gourmet</a>
            </div>

            <div className="flex items-center gap-4">
              <input type="text" placeholder="Search restaurants" className="badge" style={{minWidth:220}} />
              <AuthButtons />
            </div>
          </header>

          <main className="container mt-8 text-gray-100">{children}</main>

          <footer className="container text-sm text-gray-400 mt-12 mb-8">
            Built for demo — privacy © Inbound Gourmet
          </footer>
        </Providers>
      </body>
    </html>
  )
}
